# Databricks Apps Configuration
#
# This file configures your application for deployment to Databricks Apps.
# For more information, see: https://docs.databricks.com/en/dev-tools/databricks-apps/index.html

# Command to start the application
# Note: uvicorn will serve both API and frontend static files
command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

# Resource configuration (optional)
# Uncomment and adjust based on your needs
# resources:
#   memory: "2Gi"
#   cpu: "1"

# Unity Catalog permissions
# Grant the app service principal access to UC resources
resources:
  uc_securable:
    # Grant READ access to dominos_analytics schema
    - securable_type: SCHEMA
      securable_full_name: main.dominos_analytics
      privilege: SELECT

    # Grant READ access to dominos_realistic schema
    - securable_type: SCHEMA
      securable_full_name: main.dominos_realistic
      privilege: SELECT

    # Grant READ access to dominos_files schema (for Explorer)
    - securable_type: SCHEMA
      securable_full_name: main.dominos_files
      privilege: SELECT

    # Grant READ access to volumes in dominos_files (for file browsing and PDF preview)
    - securable_type: SCHEMA
      securable_full_name: main.dominos_files
      privilege: READ_VOLUME

    # Grant access to LLM serving endpoint
    - securable_type: SERVING_ENDPOINT
      securable_full_name: databricks-gpt-oss-120b
      privilege: EXECUTE

    # Grant access to MAS endpoint for Genie Spaces routing
    - securable_type: SERVING_ENDPOINT
      securable_full_name: mas-3d3b5439-endpoint
      privilege: EXECUTE

# Environment variables
# Note: DATABRICKS_HOST and DATABRICKS_TOKEN are automatically injected by Databricks Apps
# Do NOT explicitly define them here - Databricks Apps will handle authentication automatically
env:
  - name: DATABRICKS_HTTP_PATH
    value: /sql/1.0/warehouses/148ccb90800933a1
  - name: CATALOG
    value: main
  - name: SCHEMA
    value: dominos_analytics
  - name: LLM_MODEL_NAME
    value: databricks-gpt-oss-120b
  - name: MAS_ENDPOINT_NAME
    value: mas-3d3b5439-endpoint
